import os
import json
import uuid
from pptx import Presentation
from pptx.util import Inches


# def _generate_story(payload: dict):
#     """
#     Convert your backend structured research → pitch narrative
#     """

#     prompt = f"""
# You are a top-tier VC analyst.

# Convert this startup research into a clean pitch deck structure.

# Return STRICT JSON:

# {{
#   "title": "",
#   "problem": "",
#   "solution": "",
#   "market": "",
#   "product": "",
#   "business_model": "",
#   "competition": "",
#   "traction": "",
#   "investment_thesis": ""
# }}

# DATA:
# {json.dumps(payload, indent=2)}
# """

#     response = model.generate_content(prompt)

#     try:
#         return json.loads(response.text)
#     except:
#         cleaned = response.text.replace("```json", "").replace("```", "")
#         return json.loads(cleaned)


def _build_ppt(data: dict, output_path: str):
    prs = Presentation()

    def add_slide(title, content):
        slide_layout = prs.slides.add_slide(prs.slide_layouts[1])
        slide_layout.shapes.title.text = str(title)
        prs.slides[-1].placeholders[1].text = str(content)

    # Title slide
    slide_layout = prs.slides.add_slide(prs.slide_layouts[0])
    slide_layout.shapes.title.text = str("title", "Pitch Deck")
    slide_layout.placeholders[1].text = "Generated by AI"

    # SAFE FIELD ACCESS (prevents None crash)
    add_slide("Problem", "N/A")
    add_slide("Solution", "N/A")
    add_slide("Market", "N/A")
    add_slide("Product", "N/A")
    add_slide("Business Model", "N/A")
    add_slide("Competition", "N/A")
    add_slide("Traction", "N/A")
    add_slide("Investment Thesis", "N/A")

    # IMPORTANT: force save flush
    prs.save(output_path)

def generate_pitch_deck_file(payload: dict):
    """
    MAIN ENTRY FUNCTION CALLED FROM FLASK
    """

    # 1. Gemini creates structured pitch content
    # structured_data = _generate_story(payload)

    # 2. Create unique file per request
    file_id = str(uuid.uuid4())
    output_path = f"pitchdeck_{file_id}.pptx"

    # 3. Build PPT
    _build_ppt( output_path)

    return output_path